"use client";

import { ChevronLeft, ChevronRight, Clock3, Plus, ShoppingCart, Trash2, UtensilsCrossed, UsersRound, X } from "lucide-react";
import { useEffect, useMemo, useState } from "react";
import { addIngredientsToShoppingList, deleteMealPlanItem, loadMealPlan, mondayFor, saveMealPlanItem, type MealIngredient, type MealPlanItem, type NewMealPlanItem } from "./meal-plan-data";

type MealPlanViewProps = { householdId?: string; userId?: string; onItemsChange?: (items: MealPlanItem[]) => void; onSyncState?: (state: "saving" | "synced" | "error") => void; onShoppingChanged?: () => void };
const days = ["Mandag", "Tirsdag", "Onsdag", "Torsdag", "Fredag", "Lørdag", "Søndag"];
const shortDate = new Intl.DateTimeFormat("da-DK", { day: "numeric", month: "short" });

function weekDate(weekStart: string, dayIndex: number) { const date = new Date(`${weekStart}T12:00:00`); date.setDate(date.getDate() + dayIndex); return date; }
function moveWeek(weekStart: string, offset: number) { const date = new Date(`${weekStart}T12:00:00`); date.setDate(date.getDate() + offset * 7); return mondayFor(date); }

function MealModal({ dayOfWeek, initial, onClose, onDelete, onSave }: { dayOfWeek: number; initial: MealPlanItem | null; onClose: () => void; onDelete: () => Promise<void>; onSave: (value: NewMealPlanItem) => Promise<void> }) {
  const [title, setTitle] = useState(initial?.title ?? "");
  const [servings, setServings] = useState(initial?.servings ?? 2);
  const [duration, setDuration] = useState(initial?.durationMinutes?.toString() ?? "30");
  const [notes, setNotes] = useState(initial?.notes ?? "");
  const [ingredients, setIngredients] = useState<MealIngredient[]>(initial?.ingredients.length ? initial.ingredients : [{ name: "", quantity: null, unit: null }]);
  const [saving, setSaving] = useState(false);
  const [error, setError] = useState("");
  const updateIngredient = (index: number, patch: Partial<MealIngredient>) => setIngredients((items) => items.map((item, itemIndex) => itemIndex === index ? { ...item, ...patch } : item));
  const submit = async () => { if (!title.trim()) { setError("Skriv navnet på måltidet."); return; } setSaving(true); setError(""); try { await onSave({ dayOfWeek, mealSlot: initial?.mealSlot ?? 1, title, servings, durationMinutes: duration ? Number(duration) : null, notes: notes || null, ingredients: ingredients.filter((item) => item.name.trim()) }); onClose(); } catch (reason) { setError(reason instanceof Error ? reason.message : "Måltidet kunne ikke gemmes."); } finally { setSaving(false); } };
  return <div className="modal-backdrop" onMouseDown={onClose} role="presentation"><section aria-modal="true" className="meal-modal" onMouseDown={(event) => event.stopPropagation()} role="dialog"><button aria-label="Luk" className="modal-close" onClick={onClose} type="button"><X size={18} /></button><header><span className="modal-icon"><UtensilsCrossed size={20} /></span><div><h2>{initial ? "Redigér måltid" : `Nyt måltid · ${days[dayOfWeek - 1]}`}</h2><p>Tilføj portioner, tid, noter og ingredienser.</p></div></header><div className="meal-form-grid"><label className="field-span-2"><span>Måltid</span><input autoFocus onChange={(e) => setTitle(e.target.value)} placeholder="Fx pasta med grønt" value={title} /></label><label><span>Portioner</span><input max="50" min="1" onChange={(e) => setServings(Number(e.target.value))} type="number" value={servings} /></label><label><span>Tilberedning (min.)</span><input max="600" min="1" onChange={(e) => setDuration(e.target.value)} type="number" value={duration} /></label><label className="field-span-2"><span>Noter</span><textarea onChange={(e) => setNotes(e.target.value)} rows={2} value={notes} /></label><fieldset className="field-span-2 ingredient-fields"><legend>Ingredienser</legend>{ingredients.map((ingredient, index) => <div key={index}><input aria-label="Ingrediens" onChange={(e) => updateIngredient(index, { name: e.target.value })} placeholder="Ingrediens" value={ingredient.name} /><input aria-label="Mængde" min="0" onChange={(e) => updateIngredient(index, { quantity: e.target.value ? Number(e.target.value) : null })} placeholder="Antal" step="0.1" type="number" value={ingredient.quantity ?? ""} /><input aria-label="Enhed" onChange={(e) => updateIngredient(index, { unit: e.target.value || null })} placeholder="g, stk…" value={ingredient.unit ?? ""} /><button aria-label="Fjern ingrediens" disabled={ingredients.length === 1} onClick={() => setIngredients((items) => items.filter((_, itemIndex) => itemIndex !== index))} type="button"><X size={15} /></button></div>)}<button className="text-button" onClick={() => setIngredients((items) => [...items, { name: "", quantity: null, unit: null }])} type="button"><Plus size={14} /> Tilføj ingrediens</button></fieldset></div>{error ? <p className="modal-error" role="alert">{error}</p> : null}<footer><div>{initial ? <button className="danger-button compact" disabled={saving} onClick={() => void onDelete()} type="button"><Trash2 size={15} /> Slet</button> : null}</div><div><button className="secondary-button" onClick={onClose} type="button">Annuller</button><button className="primary-button" disabled={saving} onClick={() => void submit()} type="button">{saving ? "Gemmer…" : "Gem måltid"}</button></div></footer></section></div>;
}

export function MealPlanView({ householdId, userId, onItemsChange, onSyncState, onShoppingChanged }: MealPlanViewProps) {
  const [weekStart, setWeekStart] = useState(mondayFor());
  const [items, setItems] = useState<MealPlanItem[]>([]);
  const [editing, setEditing] = useState<{ day: number; item: MealPlanItem | null } | null>(null);
  const [message, setMessage] = useState("");
  const weekEnd = weekDate(weekStart, 6);
  const refresh = async () => { if (!householdId) return; const plan = await loadMealPlan(householdId, weekStart); setItems(plan.items); onItemsChange?.(plan.items); };
  useEffect(() => { const task = window.setTimeout(() => void refresh().catch(() => onSyncState?.("error")), 0); return () => window.clearTimeout(task); }, [householdId, weekStart]); // eslint-disable-line react-hooks/exhaustive-deps
  const grouped = useMemo(() => days.map((_, index) => items.filter((item) => item.dayOfWeek === index + 1)), [items]);
  const save = async (value: NewMealPlanItem) => { if (!householdId || !userId) throw new Error("Log ind for at gemme madplanen."); onSyncState?.("saving"); await saveMealPlanItem(householdId, userId, weekStart, { ...value, mealSlot: editing?.item?.mealSlot ?? grouped[value.dayOfWeek - 1].length + 1 }, editing?.item?.id); await refresh(); onSyncState?.("synced"); };
  const remove = async () => { if (!editing?.item || !householdId) return; onSyncState?.("saving"); await deleteMealPlanItem(householdId, editing.item.id); await refresh(); setEditing(null); onSyncState?.("synced"); };
  const addToShopping = async () => { if (!householdId || !userId) return; onSyncState?.("saving"); try { const count = await addIngredientsToShoppingList(householdId, userId, items); setMessage(count ? `${count} ingredienser er sendt til indkøbslisten.` : "Tilføj ingredienser først."); onShoppingChanged?.(); onSyncState?.("synced"); } catch { setMessage("Ingredienserne kunne ikke sendes."); onSyncState?.("error"); } };
  return <div className="meal-plan-page"><div className="module-toolbar"><div><h2>Madplan</h2><p>Planlæg flere måltider pr. dag og saml indkøbet automatisk.</p></div><button className="primary-button" disabled={!items.length} onClick={() => void addToShopping()} type="button"><ShoppingCart size={16} /> Send til indkøb</button></div><div className="meal-week-controls"><button aria-label="Forrige uge" onClick={() => setWeekStart(moveWeek(weekStart, -1))} type="button"><ChevronLeft size={17} /></button><strong>{shortDate.format(weekDate(weekStart, 0))} – {shortDate.format(weekEnd)}</strong><button aria-label="Næste uge" onClick={() => setWeekStart(moveWeek(weekStart, 1))} type="button"><ChevronRight size={17} /></button><button className="secondary-button compact" onClick={() => setWeekStart(mondayFor())} type="button">Denne uge</button></div>{message ? <p className="success-message">{message}</p> : null}<section className="meal-week-grid">{days.map((day, index) => <article key={day}><header><div><strong>{day}</strong><small>{shortDate.format(weekDate(weekStart, index))}</small></div><button aria-label={`Tilføj måltid ${day}`} onClick={() => setEditing({ day: index + 1, item: null })} type="button"><Plus size={15} /></button></header><div>{grouped[index].map((item) => <button className="meal-item-card" key={item.id} onClick={() => setEditing({ day: index + 1, item })} type="button"><strong>{item.title}</strong><span><UsersRound size={13} />{item.servings} <Clock3 size={13} />{item.durationMinutes ?? "–"} min.</span>{item.ingredients.length ? <small>{item.ingredients.length} ingredienser</small> : null}</button>)}{!grouped[index].length ? <button className="meal-empty" onClick={() => setEditing({ day: index + 1, item: null })} type="button"><Plus size={14} /> Tilføj måltid</button> : null}</div></article>)}</section>{editing ? <MealModal dayOfWeek={editing.day} initial={editing.item} onClose={() => setEditing(null)} onDelete={remove} onSave={save} /> : null}</div>;
}
